mysql:
  username: "root"
  password: ""
  address: "localhost"
  database: "duels"

create-example-kit-file: true
default-kit: "example"

arena:
  position-1: "empty"
  position-2: "empty"

messages:
  only-players: "&6[Duels] &cOnly players can use this command!"
  help:
    - ""
    - "&6[Duels] &e- Commands:"
    - "&7/duel <player name> [kit name]"
    - "&7/duel accept <player name>"
    - "&7/duel stats [player name]"
    - "&c/duel arena <setpos1/setpos2>"
    - ""
  no-permission: "&6[Duels] &cNo permission to execute this command!"
  syntax-error: "&6[Duels] &cPlease, use '/%usage%'."
  offline-player: "&6[Duels] &cThe player is offline or non-existent!"
  position-defined: "&6[Duels] &ePosition '&f%position%&e' was set successfully!"
  your-status:
    - ""
    - " &fYour status:"
    - ""
    - " &fWins: &a%wins%"
    - " &fDefeats: &c%defeats%"
    - " &fWinStreak: &e%win_streak%"
    - " &aKills: &2%kills%"
    - " &cDeaths: &4%deaths%"
    - ""
  target-status:
    - ""
    - " &f%player% status:"
    - ""
    - " &fWins: &a%wins%"
    - " &fDefeats: &c%defeats%"
    - " &fWinStreak: &e%win_streak%"
    - " &aKills: &2%kills%"
    - " &cDeaths: &4%deaths%"
    - ""
  invalid-kit: "&6[Duels] &cThe chosen kit does not exist! List of available kits: &e%kits%"
  has-a-pending-invitation: "&6[Duels] &cYou or the challenged player already have a pending dueling invitation!"
  invitation-sent: "&6[Duels] &eInvitation sent to '&7%player%&e', you will be notified of the challenger's decision!"
  invitation-received:
    - ""
    - "&6[Duels] &aYou have received a dueling invitation from player '&d%player%&a'!"
    - "&6[Duels] &aThe proposed kit is '&7%kit%&a'."
    - "&6[Duels] &eTo accept type '&b/duel accept %player%&e'!"
    - "&6[Duels] &cThe invitation will expire in &l60 seconds&c!"
    - ""
  expired-invitation: "&6[Duels] &cYou have had a dueling proposal declined (time expired)."
  thats-you: "&6[Duels] &cThat player is you!"
  no-duel: "&6[Duels] &cThis player did not challenge you to a duel!"
  duel-accepted: "&6[Duels] &aDuel accepted! You will battle against player '&e%player%&a'!"
  arena-in-use: "&6[Duels] &cThe arena is already in use at the moment, your duel has been queued, it will start soon!"
  duel-starting: "&6[Duels] &eGet ready! Duel starting in '&c%seconds%&e'."
  duel-started: "&6[Duels] &aDuel started! Good luck and may the best one win."
  queue-moved: "&6[Duels] &cAttention, it's your turn to duel! You will be pulled into battle in &l10 seconds&c!"